// menu
export const ADD_RAMEN_TYPE = "ADD_RAMEN_TYPE";
export const ADD_NOODLE_TYPE = "ADD_NOODLE_TYPE";

export const TOGGLE_EXTRA_ITEM = "TOGGLE_EXTRA_ITEM";

// cart
export const ADD_ORDER = "ADD_ORDER";
export const REMOVE_ORDER = "REMOVE_ORDER";

// auth
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const VALID_USER_ALREADY_LOGGED_IN = "VALID_USER_ALREADY_LOGGED_IN";

// checkout
export const SEND_ORDERS_INIT = "SEND_ORDERS_INIT";
export const SEND_ORDERS_SUCCESS = "SEND_ORDERS_SUCCESS";
export const SEND_ORDERS_FAIL = "SEND_ORDERS_FAIL";

// ordersHistory
export const FETCH_ORDERS_HISTORY_INIT = "FETCH_ORDERS_HISTORY_INIT";
export const FETCH_ORDERS_HISTORY_SUCCESS = "FETCH_ORDERS_HISTORY_SUCCESS";
export const FETCH_ORDERS_HISTORY_FAIL = "FETCH_ORDERS_HISTORY_FAIL";
